### ISSUE TITLE
FE - Improve "Quem Somos"

### ISSUE THREAD

**Issue by luisiul359** [Politica-Para-Todos/comentAR#167]
- Link "Quem somos" in footer to "Quem Somos" page
- Add following text before "Podes consultar aqui todo o histórico do projecto."

> A comunidade Política Para Todos nasceu no verão de 2019 com o objetivo de promover a participação ativa dos cidadãos nos processos eleitorais em Portugal. É composta por voluntários de várias partes do país e diferentes áreas profissionais. Adotamos princípios de transparência radical na nossa forma de trabalho: toda a comunicação interna está disponível numa plataforma aberta , as reuniões são gravadas e também de acesso livre. A adesão à comunidade é aberta para qualquer cidadão.

**Comment by Riscum** [comment]
Fixed with PR:
https://github.com/Politica-Para-Todos/comentAR/pull/175
