### ISSUE TITLE
BE - Add a software license

### ISSUE THREAD

**Issue by marado** [Politica-Para-Todos/comentAR#4]
Hopefully a free software one :-)

**Comment by luisiul359** [comment]
These licenses are very permissive. Anyone has some preference?
* [Apache License 2.0](https://opensource.org/licenses/Apache-2.0)
* [MIT license](https://opensource.org/licenses/Apache-2.0)
* [BSD 3-Clause "New" or "Revised" license](https://opensource.org/licenses/BSD-3-Clause)
* [BSD 2-Clause "Simplified" or "FreeBSD" license](https://opensource.org/licenses/BSD-2-Clause)
* [ISC License](http://opensource.org/licenses/ISC)

**Comment by marado** [comment]
Hi, 

Your link to the "MIT License" actually points to the Apache 2.0. Also note that MIT has several licenses, and when people refer to the "MIT License" they are usually talking about either the Expat License, or the X11 License.

For me personally, any of these licenses work, but my preference would go to the Apache License 2.0.

**Comment by inesrosete** [comment]
Copy paste error, my bad. Added Apache License 2.0.
